<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Import Project="ImageUsers.targets" />

    <ItemGroup>
        <Using Include="ApneScan.Lang.Resources" />
        <Using Include="ApneScan.Platform" />
        <Using Include="ApneScan.Testing" />
        <Using Include="ApneScan.Threading" />
        <Using Include="ApneScan.Util" />
    </ItemGroup>
    
</Project>
