<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net462</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ApneScan.Portable</RootNamespace>
    <AssemblyName>ApneScan.Portable</AssemblyName>
    <ApplicationIcon>../ApneScan.Lib/Icons/favicon.ico</ApplicationIcon>

    <Title>ApneScan</Title>
    <Product>ApneScan</Product>
  </PropertyGroup>
  
  <Import Project="..\ApneScan.Setup\targets\CommonTargets.targets" />
  
</Project>