<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net462</TargetFrameworks>
    <!-- As these are just samples, no need for "windows only api" warnings for GdiImageContext -->
    <NoWarn>CA1416</NoWarn>
  </PropertyGroup>
  
  <Import Project="..\ApneScan.Setup\targets\CommonTargets.targets" />
  <Import Project="..\ApneScan.Setup\targets\SdkUsers.targets" />
  
  <ItemGroup>
    <ProjectReference Include="..\ApneScan.Escl.Server\ApneScan.Escl.Server.csproj" />
    <ProjectReference Include="..\ApneScan.Sdk\ApneScan.Sdk.csproj" />
    <ProjectReference Include="..\ApneScan.Images.Gdi\ApneScan.Images.Gdi.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
  </ItemGroup>
  
</Project>