; Only ApneScan-translated languages are included (to avoid misleading users)
[Languages]
Name: "english";              MessagesFile: "compiler:Default.isl"
Name: "Afrikaans";            MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Afrikaans.isl";
Name: "Albanian";             MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Albanian.isl";
Name: "Arabic";               MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Arabic.isl";
; Name: "Bengali";              MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Bengali.isl";
Name: "BrazilianPortuguese";  MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\BrazilianPortuguese.isl";
Name: "Bulgarian";            MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Bulgarian.isl";
Name: "Catalan";              MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Catalan.isl";
Name: "ChineseSimplified";    MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\ChineseSimplified.isl";
Name: "ChineseTraditional";   MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\ChineseTraditional.isl";
Name: "Croatian";             MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Croatian.isl";
Name: "Czech";                MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Czech.isl";
Name: "Danish";               MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Danish.isl";
Name: "Dutch";                MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Dutch.isl";
Name: "Estonian";             MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Estonian.isl";
Name: "Farsi";                MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Farsi.isl";
Name: "Finnish";              MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Finnish.isl";
Name: "French";               MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\French.isl";
Name: "German";               MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\German.isl";
Name: "Greek";                MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Greek.isl";
Name: "Hebrew";               MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Hebrew.isl";
Name: "Hindi";                MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Hindi.isl";
Name: "Hungarian";            MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Hungarian.isl";
Name: "Indonesian";           MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Indonesian.isl";
Name: "Italian";              MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Italian.isl";
Name: "Japanese";             MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Japanese.isl";
Name: "Korean";               MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Korean.isl";
Name: "Latvian";              MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Latvian.isl";
Name: "Lithuanian";           MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Lithuanian.isl";
Name: "Norwegian";            MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Norwegian.isl";
Name: "NorwegianNynorsk";     MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\NorwegianNynorsk.isl";
Name: "Polish";               MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Polish.isl";
Name: "Portuguese";           MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Portuguese.isl";
Name: "Romanian";             MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Romanian.isl";
Name: "Russian";              MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Russian.isl";
Name: "SerbianCyrillic";      MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\SerbianCyrillic.isl";
Name: "SerbianLatin";         MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\SerbianLatin.isl";
Name: "Sinhala";              MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Sinhala.isl";
Name: "Slovak";               MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Slovak.isl";
Name: "Slovenian";            MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Slovenian.isl";
Name: "Spanish";              MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Spanish.isl";
Name: "Swedish";              MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Swedish.isl";
Name: "Thai";                 MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Thai.isl";
Name: "Turkish";              MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Turkish.isl";
Name: "Ukrainian";            MessagesFile: "C:\Program Files (x86)\Inno Setup 6\Languages\Ukrainian.isl";
; Name: "Urdu";                 MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Urdu.isl";
Name: "Vietnamese";           MessagesFile: "..\..\ApneScan.Setup\config\windows\inno-lang\Vietnamese.isl";