<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <OutputType>Exe</OutputType>
    <RootNamespace>ApneScan.Console</RootNamespace>
    <AssemblyName>ApneScan.Console</AssemblyName>

    <SelfContained>true</SelfContained>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <!-- TODO: Re-enable trimming if we can fix startup time as well as WIA being broken -->
    <PublishTrimmed>false</PublishTrimmed>
    <TrimMode>none</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

    <Title>ApneScan - Not Another PDF Scanner</Title>
    <Product>ApneScan - Not Another PDF Scanner</Product>
  </PropertyGroup>

  <Import Project="..\ApneScan.Setup\targets\CommonTargets.targets" />
  <Import Project="..\ApneScan.Setup\targets\NativeLibs.targets" />
  <Import Project="..\ApneScan.Setup\targets\SdkUsers.targets" />
  
  <ItemGroup>
    <ProjectReference Include="..\ApneScan.Images.Gdi\ApneScan.Images.Gdi.csproj" />
    <ProjectReference Include="..\ApneScan.Lib\ApneScan.Lib.csproj" />
    <ProjectReference Include="..\ApneScan.Lib.WinForms\ApneScan.Lib.WinForms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ContentWithTargetPath Include="..\ApneScan.Setup\appsettings.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Link>appsettings.xml</Link>
      <TargetPath>appsettings.xml</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>

</Project>